### ISSUE TITLE
Icons conflicting with material icons

### ISSUE THREAD

**Issue by husayt** [danilosampaio/semantic-kanban#10]
thank you very much for very useful library.

I have noticed that all the icons in the app disappear as kanban board is overriding them. icons need to be   scoped to the component only, to  not to break other elements of the UI.

**Comment by danilosampaio** [comment]
Thanks for your feedback!

It sounds like a theming problem. Semantic-ui build allows to customize the components theme:

```
@site       : 'material';  /* Loads material site defaults */
@reset      : 'default';
@header     : 'default';
@icon       : 'default';
...
```

In favor of performance, i'm using the `semantic-ui-css` module (instead of the `semantic-ui`), that is a pre-built version of semantic-ui, with all components values as 'default'.

Could you help me to configure icons to be scoped to the component only?

**Comment by husayt** [comment]
I have managed to resolve it by removing the `icon` class from my icons
